version: '3.5'

services:
  zammad:
    image: zammad/zammad:latest
    environment:
      - DATABASE_ADAPTER=postgresql
      - DATABASE_HOST=db
      - DATABASE_USER=zammad
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=zammad_production
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: zammad_production

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
