services:
  - type: web
    name: zammad-minimal
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        value: postgres://<USER>:<PASSWORD>@<HOST>:5432/<DBNAME>
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
      - key: ZAMMAD_SKIP_SEARCH_INDEX
        value: true
      - key: ZAMMAD_RAILS_PORT
        value: 8080
    ports:
      - port: 8080
        protocol: http
